version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: siakad_mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: siakad_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db

  backend:
    image: esafauzi/be-siakad:latest
    container_name: be_siakad_backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}

  frontend:
    build:
      context: ../../
      dockerfile: misc/docker/Dockerfile
    container_name: fe_siakad_frontend
    volumes:
      - ../../:/app # Mount seluruh project FE ke container
      - /app/node_modules # Hindari konflik dependency
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_BE_SIAKAD_URL: ${VITE_BE_SIAKAD_URL}
    command: npm run dev -- --host

volumes:
  mysql_data:
